spring.application.name=timetable

#DB props
spring.datasource.url=jdbc:postgresql://localhost:5432/timetable
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Server props
server.port=8080

#LM Studio props
ai.lm-studio.base-url=http://localhost:1234
ai.lm-studio.model=qwen3.5-9b
ai.lm-studio.temperature=0.1

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB